# Generated by Django 3.0.6 on 2020-05-25 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20200525_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('url', models.URLField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.Task')),
            ],
        ),
    ]
