# Generated by Django 3.0.6 on 2020-05-25 18:21

import django.core.validators
from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator, education.models.Solution.github_validator]),
        ),
    ]
